### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by AnthonyBronca** [360devin360/Sk8nBnB#1]
# General Notes:
Kanban cards should not be in the repo coding portion. 
(We will go over these this week)

# API Docs:
*Note* : We want restful routes to follow family tree hierarchy.  Example:
`<parents>/<parent>/<children>/<child>`
In situations where we have a grand child, we can omit the grand parent portion and just simplify it to parent/child.

## Tasks:
- [x] Adjust some of the routes to be geared towards backend route naming convention rather than frontend url naming conventions. Example: `/api/users/currentUser` -> `/api/users/:userId`
- [x] Readjust the `Spots` owned by the Current User` Route to be more restful. We also likely want to grab the id for faster look up.
- [x] Review all other routes to follow these conventions

# DB Diagram:
Almost there!
## Tasks
- [x] Missing username attribute in the `Users` Table
- [x] Readjust the way you handling previewImage on `Spots` Table. This should not be needed on `Spots` because we have an associated table, `SpotImages` which we can use to handle previewImage/s

# Deadline:

Please aim to complete the listed tasks by EOD on Monday, May 13th as we are looking to have all documentations approved in order to move on to the next phase of our project life cycle the following day.

**Comment by AnthonyBronca** [comment]
# DB Diagram
Approved!

# API Docs
- [x] Adjust routes to be more restful
